### ISSUE TITLE
Add Icon and/or Child component support?

### ISSUE THREAD

**Issue by mikehuebner** [n4kz/react-native-material-buttons#2]
Just wanted to know if this was in the works, just need a icon button with text. Would be awesome and if needed I could PR it.

**Comment by n4kz** [comment]
Thanks for issue! Implementation is not difficult

```javascript
/* import Button component */
import { Button } from 'react-native-material-buttons';

/* import icons */
import MaterialIcon from 'react-native-vector-icons/MaterialIcons';

/* put icon and text inside */
<Button style={{ justifyContent: 'center' }}> /* default is 'space-around' */
  <MaterialIcon />
  <Text />
</Button>
```

Just do not want to have `react-native-vector-icons` as direct dependency due to complicated installation. Also raised buttons can be used, as icon in `react-native-vector-icons` are `Text` nodes. If your icon is binary, `<MaterialIcon />` can be replaced with `<Image />` with appropriate styles.
